# Generated by Django 5.0.1 on 2024-02-09 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_good_good_category_remove_good_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
