# Generated by Django 5.0.1 on 2024-02-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='good',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='good',
            name='title',
        ),
        migrations.AddField(
            model_name='good',
            name='name',
            field=models.CharField(default=1, max_length=200, verbose_name='Наименование товара'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.TextField(verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
    ]
