# Generated by Django 5.0.1 on 2024-02-17 06:18

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_category_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='img',
            field=models.ImageField(default=1, upload_to=main.models.good_directory_path),
            preserve_default=False,
        ),
    ]
